databases:
  - name: railway
    databaseName: PostgreSQL
    user: postgres

services:
  - type: web
    name: app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4