# Generated by Django 4.1.1 on 2022-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_packages_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='departure_return_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='departure_time',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_excluded',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_included',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='return_time',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
