# Generated by Django 4.1.1 on 2022-09-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_booking_daydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydetails',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='daydetails',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
