# Generated by Django 4.1.1 on 2022-09-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_daydetails_description_daydetails_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydetails',
            name='day',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1),
        ),
    ]
