# Generated by Django 4.1.1 on 2022-09-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_testimonial_alter_daydetails_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='package',
            old_name='departure_return_location',
            new_name='departure_location',
        ),
        migrations.AddField(
            model_name='package',
            name='max_altitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='return_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_excluded',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_included',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.gradechoice'),
        ),
    ]
