# Generated by Django 4.1.1 on 2022-09-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_gradechoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='daydetails',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.daychoices'),
        ),
    ]
