# Generated by Django 4.1.1 on 2022-09-18 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_daychoices_alter_daydetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydetails',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.daychoices'),
        ),
    ]
