# Generated by Django 4.1.1 on 2022-09-18 06:42

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_daydetails_day_delete_daychoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='daydetails',
            name='day',
            field=models.IntegerField(default=1, verbose_name=project.models.DayChoice),
        ),
    ]
