# Generated by Django 4.1.1 on 2022-09-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_daychoice_alter_daydetails_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydetails',
            name='day',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten'), (11, 'Eleven'), (12, 'Tweleve'), (13, 'Thirteen'), (14, 'Fourteen'), (15, 'Fifteen'), (16, 'SixTeen'), (17, 'SevenTeen'), (18, 'Eighteen'), (19, 'Ninteen'), (20, 'Twenty'), (21, 'Twenty One'), (22, 'Twenty Two'), (23, 'Twenty Three'), (24, 'Twenty Four'), (25, 'Twenty Five'), (26, 'Twenty Six'), (27, 'Twenty Seven'), (28, 'Twenty Eight'), (29, 'Twenty Nine'), (30, 'Thirty')], default=1),
        ),
    ]
