# Generated by Django 4.1.1 on 2022-09-18 10:07

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to=project.models.upload_to, verbose_name='image'),
        ),
    ]
