# Generated by Django 4.1.1 on 2022-09-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_category_alter_package_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.category'),
        ),
    ]
