# Generated by Django 4.1.1 on 2022-09-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_alter_package_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='grade',
        ),
    ]
