# Generated by Django 4.1.1 on 2022-09-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_remove_package_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.gradechoice'),
        ),
    ]
