# Generated by Django 4.1.1 on 2022-09-18 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_subcategory_category_alter_subcategory_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.subcategory'),
        ),
    ]
