# Generated by Django 4.1.1 on 2022-09-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_package_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
