# Generated by Django 4.1.1 on 2022-09-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2500, null=True)),
                ('answer', models.TextField(max_length=8000, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.package')),
            ],
        ),
    ]
