# Generated by Django 4.1.1 on 2022-09-27 08:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='additional_information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
